### USER SERVICE

### GET User Service Health Check
GET http://localhost:8000/users/healthz
Authorization: {{auth_token}}
Accept: application/json

### POST Actuator 'refresh'
POST http://localhost:8000/users/actuator/refresh
Authorization: {{auth_token}}

### POST Actuator 'busrefresh'
POST http://localhost:8000/users/actuator/busrefresh
Authorization: {{auth_token}}

### POST Actuator 'busrefresh' (Through api gateway)
POST http://localhost:8000/actuator/busrefresh

### POST signup
POST http://localhost:8000/users/signup
Content-Type: application/json

{
    "email": "noreply999@noreply.com",
    "name": "cwchoiit",
    "password": "1234"
}

### POST login
POST http://localhost:8000/users/login
Content-Type: application/json

{
  "email": "noreply@noreply.com",
  "password": "1234"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}

### GET Users
GET http://localhost:8000/users?page=1&pageSize=10
Authorization: {{auth_token}}
Accept: application/json

### GET User
GET http://localhost:8000/users/152759595850260480
Authorization: {{auth_token}}
Accept: application/json

### ORDERS SERVICE

### GET Orders Service Health check
GET http://localhost:8000/orders/healthz
Authorization: {{auth_token}}
Accept: application/json

### GET Orders by UserId
GET http://localhost:8000/orders/152759595850260480?page=1&pageSize=10
Authorization: {{auth_token}}
Accept: application/json

### POST Orders Service Create
POST http://localhost:8000/orders/152759595850260480
Authorization: {{auth_token}}
Accept: application/json
Content-Type: application/json

{
  "productId": 154489845712207872,
  "quantity": 1,
  "unitPrice": 5000000
}

### CATALOG SERVICE

### GET Catalog Service Health Check
GET http://localhost:8000/catalogs/healthz
Accept: application/json

### POST Catalog Service Create
POST http://localhost:8000/catalogs
Accept: application/json
Content-Type: application/json

{
    "productName": "Macbook M4",
    "stock": 1000,
    "unitPrice": 5000000
}