# USER SERVICE

### GET User Service Health Check
GET http://localhost:8000/users/healthz
Authorization: {{auth_token}}
Accept: application/json

### POST Actuator 'refresh'
POST http://localhost:8000/users/actuator/refresh
Authorization: {{auth_token}}

### POST Actuator 'busrefresh'
POST http://localhost:8000/users/actuator/busrefresh
Authorization: {{auth_token}}

### POST Actuator 'busrefresh' (Through api gateway)
POST http://localhost:8000/actuator/busrefresh

### POST signup
POST http://localhost:8000/users/signup
Content-Type: application/json

{
    "email": "noreply999@noreply.com",
    "name": "cwchoiit",
    "password": "1234"
}

### POST login
POST http://localhost:8000/users/login
Content-Type: application/json

{
  "email": "noreply@noreply.com",
  "password": "1234"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}

### GET Users
GET http://localhost:8000/users?page=1&pageSize=10
Authorization: {{auth_token}}
Accept: application/json

### GET User
GET http://localhost:8000/users/149395304454860800
Authorization: {{auth_token}}
Accept: application/json


# CATALOG SERVICE

### GET Catalog Service Health Check
GET http://localhost:8000/catalogs/healthz
Accept: application/json