# USER SERVICE

### GET User Service Health Check
GET http://localhost:8000/users/healthz
Accept: application/json

### POST create user
POST http://localhost:8000/users
Content-Type: application/json

{
    "email": "noreply@noreply.com",
    "name": "cwchoiit",
    "password": "1234"
}

### GET Users
GET http://localhost:8000/users?page=1&pageSize=10
Accept: application/json

### GET User
GET http://localhost:8000/users/149395304454860800
Accept: application/json


# CATALOG SERVICE

### GET Catalog Service Health Check
GET http://localhost:8000/catalogs/healthz
Accept: application/json